version: "3"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  godo:
    image: godo:latest
    environment:
      JWT_SECRET: "${JWT_SECRET}"
      DB_CLIENT: "${DB_CLIENT}"
      DB_CONN: "${DB_CONN}"
      GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
      GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
    ports:
      - "${PORT}:8080"
    depends_on:
      - mysql
volumes:
  mysqldata: